;  ADDJOB / PO - D11
;
;		CREATED: 02/06/94
;		AUTHOR:  DIANA K. SCHEPPA
;
;		THIS PROGRAM PULLS THE VENDOR PART # INTO THE JOB NUMBER
;		IN THE PORLIN FILE
;
;
RECORD PORLIN
	.INCLUDE 'DEF:RD152A.DEF'

RECORD
	V	,D1
	SWITCH	,D1
	RECIN	,D5
	RECOUT	,D5
	READ	,D1	,0
	WRITE	,D1	,1
	LOKCTL	,D1
	KEY	,A15
	BSEND	,D5
	BSMID	,D5
	SRCCTL	,D1
	LSTITM	,A15
	BLANKS	,A20
	L	,D2

PROC
	XCALL TERID (V)
	SWITCH = 1
	XCALL FILES (1,'U',152,SWITCH)		;FILE # 152 - PORLIN FILE
	IF (SWITCH.EQ.9) GOTO INUSE

	XCALL OUTPT (1,1,2,'ADD P/N # INTO JOB NUMBER FIELD',V)
	XCALL OUTPT(20,1,1,'READING RECORD NUMBER:',1)
	XCALL OUTPT(21,1,1,'UPDATING RECORD NUMBER:',1)
	RECIN = 1
REDHST,
	INCR RECIN
	LOKCTL = 1
	XCALL IO (1,PORLIN,RECIN,READ,LOKCTL)
	IF (LOKCTL.EQ.2) GOTO EOF
	IF (PORLIN(1,5).EQ.']]]]]') GOTO EOF
	XCALL OUTPT(20,26,0,RECIN,1)
	IF (LVITMN.EQ.BLANKS) GOTO REDHST
	L =
UPDIT,
	INCR L
	IF (L.GT.20) GOTO REDHST
	IF (LVITMN(L,L).EQ.' ') GOTO UPDIT2
	GOTO UPDIT
UPDIT2,
	IF (L.NE.7) GOTO REDHST
	LJOBNO = LVITMN(1,6)
	LOKCTL = 1
	XCALL IO (1,PORLIN,RECIN,WRITE,LOKCTL)
	INCR RECOUT
	XCALL OUTPT(21,26,0,RECOUT,1)
	GOTO REDHST
EOF,
CLOSE,
	XCALL FILES (1,'I',41,4)
	XCALL PGCHN ('IM:IMMENU',1)
;*************************************************************************
INUSE,
	XCALL MESAG('THE PORLIN FILE IS IN USE ... TRY LATER',2)
	XCALL PGCHN ('IM:IMMENU',1)
END
