; CLRMNU.PO
;
;			CREATED: 11/30/94
;			AUTHOR:	 DIANA K. SCHEPPA
;
;
;		PURCHASE ORDERS CLEAR/RESET/PURGE FUNCTIONS        
;

	.DEFINE POOLSIZE	,25000
	.DEFINE WNDCHNL		,15
	.DEFINE MAXWINS		,5
	.INCLUDE 'WND:WINDOWS.DEF'

RECORD CHAIN
	.INCLUDE 'DEF:CHAIN.DEF'

RECORD FILCHN
		,A9,	'UT:CHAIN.'
	EXT	,A3

;*** NEED TO CHANGE ONLY THESE VARIABLES FOR EACH NEW MENU TO MAKE UNIQUE
RECORD VARS
	XPKG	,A2,	'PO'			;APPLICATION ID (FROM MENUS.NSM)
	XID	,A2,	'MB'			;MENU ID (FROM MENUS.NSM)
	MTITLE	,A*,	'CLEAR/RESET/PURGE FUNCTIONS'	;TITLE TO DISPLAY ON MENU
	PROGNM	,A9,	'PO:CLRMNU'		;NAME OF THIS MENU
	PRGMNU	,A9,	'PO:POSFMN'		;NAME OF MENU TO RETURN BACK TO
;************

RECORD
	WNDW_1	,D3
	V	,D1
	TNUM	,D3
	ERRFLG	,D1
	READ	,D1,	0
	WRITE	,D1,	1
	LOKCTL	,D1
	PGM	,D2
	PGNAME	,A9
	XPASS	,A9
	XSEQ	,D2


PROC

	XCALL TERID (V)
	XCALL TNMBR(TNUM)
	EXT = TNUM,'XXX'
	
	OPEN (6,U,FILCHN)
	LOKCTL = 1
	XCALL ISIO (6,CHAIN,1,READ,LOKCTL)

	XCALL W_INIT(POOLSIZE,WNDCHNL,MAXWINS)
	XCALL XMENU (WNDW_1,MTITLE)	;CREATES WINDOW AND DISPLAYS IT

;** Any customization of window, put here
;**	
	XCALL XAUTH (WNDW_1,CPASS,XPKG,XID,XSEQ,PGNAME,ERRFLG)  ;DISPLAY MENU ITEMS
	IF (ERRFLG.EQ.1) GOTO NOAUTH
	IF (ERRFLG.EQ.2) GOTO ENDOFF

	CPGM = PROGNM	
	LOKCTL = 1
	XCALL ISIO (6,CHAIN,1,WRITE,LOKCTL)
	CLOSE 6		

	XCALL W_PROC (WP_REMOVE,WNDW_1)
	XCALL W_EXIT
	XCALL PGCHN (PGNAME,1)
NOAUTH,
	XCALL MESAG ('USER NOT AUTHORIZED FOR THIS MENU',1)
ENDOFF,
	CLOSE 6
	XCALL W_PROC (WP_REMOVE,WNDW_1)
	XCALL W_EXIT
	XCALL PGCHN (PRGMNU,1)

END
