!	DPNSTP.POR
!
EDIT/EXEC:'IN:BDATE.POR' STRIP
EDIT/EXEC:'BDATE.TMP' DIP
COPY IN:BDATE.POR OUT:BDATE.BAK
COPY BDATE.TMP OUT:BDATE.POR
DEL/LOG BDATE.TMP

EDIT/EXEC:'IN:BYJOB.POR' STRIP
EDIT/EXEC:'BYJOB.TMP' DIP
COPY IN:BYJOB.POR OUT:BYJOB.BAK
COPY BYJOB.TMP OUT:BYJOB.POR
DEL/LOG BYJOB.TMP

EDIT/EXEC:'IN:BYITM.POR' STRIP
EDIT/EXEC:'BYITM.TMP' DIP
COPY IN:BYITM.POR OUT:BYITM.BAK
COPY BYITM.TMP OUT:BYITM.POR
DEL/LOG BYITM.TMP

EDIT/EXEC:'IN:BYVEN.POR' STRIP
EDIT/EXEC:'BYVEN.TMP' DIP
COPY IN:BYVEN.POR OUT:BYVEN.BAK
COPY BYVEN.TMP OUT:BYVEN.POR
DEL/LOG BYVEN.TMP

EDIT/EXEC:'IN:CLVNAV.POR' STRIP
EDIT/EXEC:'CLVNAV.TMP' DIP
COPY IN:CLVNAV.POR OUT:CLVNAV.BAK
COPY CLVNAV.TMP OUT:CLVNAV.POR
DEL/LOG CLVNAV.TMP

EDIT/EXEC:'IN:GDATE.POR' STRIP
EDIT/EXEC:'GDATE.TMP' DIP
COPY IN:GDATE.POR OUT:GDATE.BAK
COPY GDATE.TMP OUT:GDATE.POR
DEL/LOG GDATE.TMP

EDIT/EXEC:'IN:INITPO.POR' STRIP
EDIT/EXEC:'INITPO.TMP' DIP
COPY IN:INITPO.POR OUT:INITPO.BAK
COPY INITPO.TMP OUT:INITPO.POR
DEL/LOG INITPO.TMP

EDIT/EXEC:'IN:LINE1.POR' STRIP
EDIT/EXEC:'LINE1.TMP' DIP
COPY IN:LINE1.POR OUT:LINE1.BAK
COPY LINE1.TMP OUT:LINE1.POR
DEL/LOG LINE1.TMP

EDIT/EXEC:'IN:LINE2.POR' STRIP
EDIT/EXEC:'LINE2.TMP' DIP
COPY IN:LINE2.POR OUT:LINE2.BAK
COPY LINE2.TMP OUT:LINE2.POR
DEL/LOG LINE2.TMP

EDIT/EXEC:'IN:ORGPOA.POR' STRIP
EDIT/EXEC:'ORGPOA.TMP' DIP
COPY IN:ORGPOA.POR OUT:ORGPOA.BAK
COPY ORGPOA.TMP OUT:ORGPOA.POR
DEL/LOG ORGPOA.TMP

EDIT/EXEC:'IN:ORGPOH.POR' STRIP
EDIT/EXEC:'ORGPOH.TMP' DIP
COPY IN:ORGPOH.POR OUT:ORGPOH.BAK
COPY ORGPOH.TMP OUT:ORGPOH.POR
DEL/LOG ORGPOH.TMP

EDIT/EXEC:'IN:ORGPOL.POR' STRIP
EDIT/EXEC:'ORGPOL.TMP' DIP
COPY IN:ORGPOL.POR OUT:ORGPOL.BAK
COPY ORGPOL.TMP OUT:ORGPOL.POR
DEL/LOG ORGPOL.TMP

EDIT/EXEC:'IN:ORGPOT.POR' STRIP
EDIT/EXEC:'ORGPOT.TMP' DIP
COPY IN:ORGPOT.POR OUT:ORGPOT.BAK
COPY ORGPOT.TMP OUT:ORGPOT.POR
DEL/LOG ORGPOT.TMP

EDIT/EXEC:'IN:POACNT.POR' STRIP
EDIT/EXEC:'POACNT.TMP' DIP
COPY IN:POACNT.POR OUT:POACNT.BAK
COPY POACNT.TMP OUT:POACNT.POR
DEL/LOG POACNT.TMP

EDIT/EXEC:'IN:POADDH.POR' STRIP
EDIT/EXEC:'POADDH.TMP' DIP
COPY IN:POADDH.POR OUT:POADDH.BAK
COPY POADDH.TMP OUT:POADDH.POR
DEL/LOG POADDH.TMP

EDIT/EXEC:'IN:POADDL.POR' STRIP
EDIT/EXEC:'POADDL.TMP' DIP
COPY IN:POADDL.POR OUT:POADDL.BAK
COPY POADDL.TMP OUT:POADDL.POR
DEL/LOG POADDL.TMP

EDIT/EXEC:'IN:POALGN.POR' STRIP
EDIT/EXEC:'POALGN.TMP' DIP
COPY IN:POALGN.POR OUT:POALGN.BAK
COPY POALGN.TMP OUT:POALGN.POR
DEL/LOG POALGN.TMP

EDIT/EXEC:'IN:POAUDT.POR' STRIP
EDIT/EXEC:'POAUDT.TMP' DIP
COPY IN:POAUDT.POR OUT:POAUDT.BAK
COPY POAUDT.TMP OUT:POAUDT.POR
DEL/LOG POAUDT.TMP

EDIT/EXEC:'IN:POBRLS.POR' STRIP
EDIT/EXEC:'POBRLS.TMP' DIP
COPY IN:POBRLS.POR OUT:POBRLS.BAK
COPY POBRLS.TMP OUT:POBRLS.POR
DEL/LOG POBRLS.TMP

EDIT/EXEC:'IN:POCASH.POR' STRIP
EDIT/EXEC:'POCASH.TMP' DIP
COPY IN:POCASH.POR OUT:POCASH.BAK
COPY POCASH.TMP OUT:POCASH.POR
DEL/LOG POCASH.TMP

EDIT/EXEC:'IN:POCNGH.POR' STRIP
EDIT/EXEC:'POCNGH.TMP' DIP
COPY IN:POCNGH.POR OUT:POCNGH.BAK
COPY POCNGH.TMP OUT:POCNGH.POR
DEL/LOG POCNGH.TMP

EDIT/EXEC:'IN:POCNGL.POR' STRIP
EDIT/EXEC:'POCNGL.TMP' DIP
COPY IN:POCNGL.POR OUT:POCNGL.BAK
COPY POCNGL.TMP OUT:POCNGL.POR
DEL/LOG POCNGL.TMP

EDIT/EXEC:'IN:POCOMM.POR' STRIP
EDIT/EXEC:'POCOMM.TMP' DIP
COPY IN:POCOMM.POR OUT:POCOMM.BAK
COPY POCOMM.TMP OUT:POCOMM.POR
DEL/LOG POCOMM.TMP

EDIT/EXEC:'IN:POEDLS.POR' STRIP
EDIT/EXEC:'POEDLS.TMP' DIP
COPY IN:POEDLS.POR OUT:POEDLS.BAK
COPY POEDLS.TMP OUT:POEDLS.POR
DEL/LOG POEDLS.TMP

EDIT/EXEC:'IN:POENMN.POR' STRIP
EDIT/EXEC:'POENMN.TMP' DIP
COPY IN:POENMN.POR OUT:POENMN.BAK
COPY POENMN.TMP OUT:POENMN.POR
DEL/LOG POENMN.TMP

EDIT/EXEC:'IN:POFILS.POR' STRIP
EDIT/EXEC:'POFILS.TMP' DIP
COPY IN:POFILS.POR OUT:POFILS.BAK
COPY POFILS.TMP OUT:POFILS.POR
DEL/LOG POFILS.TMP

EDIT/EXEC:'IN:POHCNT.POR' STRIP
EDIT/EXEC:'POHCNT.TMP' DIP
COPY IN:POHCNT.POR OUT:POHCNT.BAK
COPY POHCNT.TMP OUT:POHCNT.POR
DEL/LOG POHCNT.TMP

EDIT/EXEC:'IN:POHDEL.POR' STRIP
EDIT/EXEC:'POHDEL.TMP' DIP
COPY IN:POHDEL.POR OUT:POHDEL.BAK
COPY POHDEL.TMP OUT:POHDEL.POR
DEL/LOG POHDEL.TMP

EDIT/EXEC:'IN:POIMNU.POR' STRIP
EDIT/EXEC:'POIMNU.TMP' DIP
COPY IN:POIMNU.POR OUT:POIMNU.BAK
COPY POIMNU.TMP OUT:POIMNU.POR
DEL/LOG POIMNU.TMP

EDIT/EXEC:'IN:POINQI.POR' STRIP
EDIT/EXEC:'POINQI.TMP' DIP
COPY IN:POINQI.POR OUT:POINQI.BAK
COPY POINQI.TMP OUT:POINQI.POR
DEL/LOG POINQI.TMP

EDIT/EXEC:'IN:POITMC.POR' STRIP
EDIT/EXEC:'POITMC.TMP' DIP
COPY IN:POITMC.POR OUT:POITMC.BAK
COPY POITMC.TMP OUT:POITMC.POR
DEL/LOG POITMC.TMP

EDIT/EXEC:'IN:POITMR.POR' STRIP
EDIT/EXEC:'POITMR.TMP' DIP
COPY IN:POITMR.POR OUT:POITMR.BAK
COPY POITMR.TMP OUT:POITMR.POR
DEL/LOG POITMR.TMP

EDIT/EXEC:'IN:POLCNT.POR' STRIP
EDIT/EXEC:'POLCNT.TMP' DIP
COPY IN:POLCNT.POR OUT:POLCNT.BAK
COPY POLCNT.TMP OUT:POLCNT.POR
DEL/LOG POLCNT.TMP

EDIT/EXEC:'IN:POLDEL.POR' STRIP
EDIT/EXEC:'POLDEL.TMP' DIP
COPY IN:POLDEL.POR OUT:POLDEL.BAK
COPY POLDEL.TMP OUT:POLDEL.POR
DEL/LOG POLDEL.TMP

EDIT/EXEC:'IN:POMENU.POR' STRIP
EDIT/EXEC:'POMENU.TMP' DIP
COPY IN:POMENU.POR OUT:POMENU.BAK
COPY POMENU.TMP OUT:POMENU.POR
DEL/LOG POMENU.TMP

EDIT/EXEC:'IN:POPRNT.POR' STRIP
EDIT/EXEC:'POPRNT.TMP' DIP
COPY IN:POPRNT.POR OUT:POPRNT.BAK
COPY POPRNT.TMP OUT:POPRNT.POR
DEL/LOG POPRNT.TMP

EDIT/EXEC:'IN:POPUPD.POR' STRIP
EDIT/EXEC:'POPUPD.TMP' DIP
COPY IN:POPUPD.POR OUT:POPUPD.BAK
COPY POPUPD.TMP OUT:POPUPD.POR
DEL/LOG POPUPD.TMP

EDIT/EXEC:'IN:PORDFL.POR' STRIP
EDIT/EXEC:'PORDFL.TMP' DIP
COPY IN:PORDFL.POR OUT:PORDFL.BAK
COPY PORDFL.TMP OUT:PORDFL.POR
DEL/LOG PORDFL.TMP

EDIT/EXEC:'IN:PORECV.POR' STRIP
EDIT/EXEC:'PORECV.TMP' DIP
COPY IN:PORECV.POR OUT:PORECV.BAK
COPY PORECV.TMP OUT:PORECV.POR
DEL/LOG PORECV.TMP

EDIT/EXEC:'IN:POSCHD.POR' STRIP
EDIT/EXEC:'POSCHD.TMP' DIP
COPY IN:POSCHD.POR OUT:POSCHD.BAK
COPY POSCHD.TMP OUT:POSCHD.POR
DEL/LOG POSCHD.TMP

EDIT/EXEC:'IN:POSCHI.POR' STRIP
EDIT/EXEC:'POSCHI.TMP' DIP
COPY IN:POSCHI.POR OUT:POSCHI.BAK
COPY POSCHI.TMP OUT:POSCHI.POR
DEL/LOG POSCHI.TMP

EDIT/EXEC:'IN:POSCHJ.POR' STRIP
EDIT/EXEC:'POSCHJ.TMP' DIP
COPY IN:POSCHJ.POR OUT:POSCHJ.BAK
COPY POSCHJ.TMP OUT:POSCHJ.POR
DEL/LOG POSCHJ.TMP

EDIT/EXEC:'IN:POSCHV.POR' STRIP
EDIT/EXEC:'POSCHV.TMP' DIP
COPY IN:POSCHV.POR OUT:POSCHV.BAK
COPY POSCHV.TMP OUT:POSCHV.POR
DEL/LOG POSCHV.TMP

EDIT/EXEC:'IN:POSCRG.POR' STRIP
EDIT/EXEC:'POSCRG.TMP' DIP
COPY IN:POSCRG.POR OUT:POSCRG.BAK
COPY POSCRG.TMP OUT:POSCRG.POR
DEL/LOG POSCRG.TMP

EDIT/EXEC:'IN:POSFMN.POR' STRIP
EDIT/EXEC:'POSFMN.TMP' DIP
COPY IN:POSFMN.POR OUT:POSFMN.BAK
COPY POSFMN.TMP OUT:POSFMN.POR
DEL/LOG POSFMN.TMP

EDIT/EXEC:'IN:POTBLL.POR' STRIP
EDIT/EXEC:'POTBLL.TMP' DIP
COPY IN:POTBLL.POR OUT:POTBLL.BAK
COPY POTBLL.TMP OUT:POTBLL.POR
DEL/LOG POTBLL.TMP

EDIT/EXEC:'IN:POTBLM.POR' STRIP
EDIT/EXEC:'POTBLM.TMP' DIP
COPY IN:POTBLM.POR OUT:POTBLM.BAK
COPY POTBLM.TMP OUT:POTBLM.POR
DEL/LOG POTBLM.TMP

EDIT/EXEC:'IN:POTCNT.POR' STRIP
EDIT/EXEC:'POTCNT.TMP' DIP
COPY IN:POTCNT.POR OUT:POTCNT.BAK
COPY POTCNT.TMP OUT:POTCNT.POR
DEL/LOG POTCNT.TMP

EDIT/EXEC:'IN:POVANL.POR' STRIP
EDIT/EXEC:'POVANL.TMP' DIP
COPY IN:POVANL.POR OUT:POVANL.BAK
COPY POVANL.TMP OUT:POVANL.POR
DEL/LOG POVANL.TMP

EDIT/EXEC:'IN:PRSPRP.POR' STRIP
EDIT/EXEC:'PRSPRP.TMP' DIP
COPY IN:PRSPRP.POR OUT:PRSPRP.BAK
COPY PRSPRP.TMP OUT:PRSPRP.POR
DEL/LOG PRSPRP.TMP

EDIT/EXEC:'IN:PRTCOM.POR' STRIP
EDIT/EXEC:'PRTCOM.TMP' DIP
COPY IN:PRTCOM.POR OUT:PRTCOM.BAK
COPY PRTCOM.TMP OUT:PRTCOM.POR
DEL/LOG PRTCOM.TMP

EDIT/EXEC:'IN:PVNDFT.POR' STRIP
EDIT/EXEC:'PVNDFT.TMP' DIP
COPY IN:PVNDFT.POR OUT:PVNDFT.BAK
COPY PVNDFT.TMP OUT:PVNDFT.POR
DEL/LOG PVNDFT.TMP

EDIT/EXEC:'IN:PVNLST.POR' STRIP
EDIT/EXEC:'PVNLST.TMP' DIP
COPY IN:PVNLST.POR OUT:PVNLST.BAK
COPY PVNLST.TMP OUT:PVNLST.POR
DEL/LOG PVNLST.TMP

EDIT/EXEC:'IN:PVNMNT.POR' STRIP
EDIT/EXEC:'PVNMNT.TMP' DIP
COPY IN:PVNMNT.POR OUT:PVNMNT.BAK
COPY PVNMNT.TMP OUT:PVNMNT.POR
DEL/LOG PVNMNT.TMP

EDIT/EXEC:'IN:SCRN1.POR' STRIP
EDIT/EXEC:'SCRN1.TMP' DIP
COPY IN:SCRN1.POR OUT:SCRN1.BAK
COPY SCRN1.TMP OUT:SCRN1.POR
DEL/LOG SCRN1.TMP

EDIT/EXEC:'IN:SCRN2.POR' STRIP
EDIT/EXEC:'SCRN2.TMP' DIP
COPY IN:SCRN2.POR OUT:SCRN2.BAK
COPY SCRN2.TMP OUT:SCRN2.POR
DEL/LOG SCRN2.TMP

EDIT/EXEC:'IN:SRTCOM.POR' STRIP
EDIT/EXEC:'SRTCOM.TMP' DIP
COPY IN:SRTCOM.POR OUT:SRTCOM.BAK
COPY SRTCOM.TMP OUT:SRTCOM.POR
DEL/LOG SRTCOM.TMP

EDIT/EXEC:'IN:SRTPOA.POR' STRIP
EDIT/EXEC:'SRTPOA.TMP' DIP
COPY IN:SRTPOA.POR OUT:SRTPOA.BAK
COPY SRTPOA.TMP OUT:SRTPOA.POR
DEL/LOG SRTPOA.TMP

EDIT/EXEC:'IN:SRTPOH.POR' STRIP
EDIT/EXEC:'SRTPOH.TMP' DIP
COPY IN:SRTPOH.POR OUT:SRTPOH.BAK
COPY SRTPOH.TMP OUT:SRTPOH.POR
DEL/LOG SRTPOH.TMP

EDIT/EXEC:'IN:SRTPOI.POR' STRIP
EDIT/EXEC:'SRTPOI.TMP' DIP
COPY IN:SRTPOI.POR OUT:SRTPOI.BAK
COPY SRTPOI.TMP OUT:SRTPOI.POR
DEL/LOG SRTPOI.TMP

EDIT/EXEC:'IN:SRTPOL.POR' STRIP
EDIT/EXEC:'SRTPOL.TMP' DIP
COPY IN:SRTPOL.POR OUT:SRTPOL.BAK
COPY SRTPOL.TMP OUT:SRTPOL.POR
DEL/LOG SRTPOL.TMP

EDIT/EXEC:'IN:SRTPOS.POR' STRIP
EDIT/EXEC:'SRTPOS.TMP' DIP
COPY IN:SRTPOS.POR OUT:SRTPOS.BAK
COPY SRTPOS.TMP OUT:SRTPOS.POR
DEL/LOG SRTPOS.TMP

EDIT/EXEC:'IN:SRTPOT.POR' STRIP
EDIT/EXEC:'SRTPOT.TMP' DIP
COPY IN:SRTPOT.POR OUT:SRTPOT.BAK
COPY SRTPOT.TMP OUT:SRTPOT.POR
DEL/LOG SRTPOT.TMP

EDIT/EXEC:'IN:UNPROT.POR' STRIP
EDIT/EXEC:'UNPROT.TMP' DIP
COPY IN:UNPROT.POR OUT:UNPROT.BAK
COPY UNPROT.TMP OUT:UNPROT.POR
DEL/LOG UNPROT.TMP

EDIT/EXEC:'IN:VIRPRT.POR' STRIP
EDIT/EXEC:'VIRPRT.TMP' DIP
COPY IN:VIRPRT.POR OUT:VIRPRT.BAK
COPY VIRPRT.TMP OUT:VIRPRT.POR
DEL/LOG VIRPRT.TMP

