; INVINQ / PO - D11
;
;		CREATED:  21-FEB-94
;		AUTHOR :  DIANA K. SCHEPPA
;
;		SHOWS ENTIRE USAGE HISTORY BY ITEM FROM THE INVHST FILE
;
RECORD ITMIDX
	.INCLUDE 'DEF:RD042A.DEF'

RECORD ITMMAS
	.INCLUDE 'DEF:RD041A.DEF'

RECORD	,X
	.INCLUDE 'DEF:RD041B.DEF'

RECORD INVHST
	.INCLUDE 'DEF:RD216A.DEF'

RECORD TITLE
		,A18,'ITEM USAGE HISTORY'

RECORD HDR1
		,A11,	'ITEM NUMBER'
		,A7
		,A8,	'ACT DATE'
		,A3
		,A8,	'QUANTITY'
		,A3
		,A14,	'NU ITEM NUMBER'
		,A3
		,A4,	'TYPE'
		,A71

RECORD
	ASOFDT	,A8
	HLDATE	,D6
	STDATE	,D6
	SDATE	,D6
	EDATE	,D6
	ADATE	,A8
	ALL	,A10
	DASHES	,A40,'----------------------------------------'
	DTMASK	,A8,'XX/XX/XX'
	ENTRY	,A15
	ENDNO	,A15
	FSTFLG	,D1,1
	INXCTL	,D1
	LINCNT	,D2,61
	LPSW	,D1
	PGCNT	,D3
	PLINE	,A132
	PRTCNT	,D5
	PRTCTL	,D3
	PRTFIL	,A14
	PRTTYP	,A1
	RPTNUM	,D3
	SAVLPS	,D1
	SPLFIL	,A14
	SRCCTL	,D1
	STRTNO	,A15
	STXCTL	,D1
	SWITCH	,D1,1
	LOKCTL	,D1
	READ	,D1,	0
	WRITE	,D1,	1
	V	,D1,1
	WTARG	,D1,2


PROC
	XCALL TERID (V)
	V = 1
	XCALL FILES(2,'I',42,SWITCH)		;FILE # 42 -- ITMIDX FILE
	IF (SWITCH.EQ.9) GO TO EXIT
	XCALL FILES(8,'SI',216,SWITCH)		;FILE # 216 - INVHST FILE
	IF (SWITCH.NE.9) GO TO OPEN1
	CALL CLOSE1
	GO TO EXIT
OPEN1,
	XCALL FILES(1,'I',41,SWITCH)		;FILE # 41 -- ITMMAS FILE
	IF (SWITCH.EQ.9) GO TO END
BEGIN,
	XCALL OUTPT(1,1,2,'ITEM USAGE HISTORY',V)
	LINCNT = 61
	SPLFIL (5,6) = 'FG'
SDAT,
	HLDATE=
	XCALL OUTPT (8,20,2,'ENTER STARTING ACTIVITY DATE',V)
	XCALL INPUT (8,52,6,0,'DE',ENTRY,INXCTL,V)
	GO TO (SDAT,END), INXCTL
	HLDATE = ENTRY (1,6)
	STDATE = HLDATE
	SDATE(1,2) = HLDATE(5,6)
	SDATE(3,6) = HLDATE(1,4)
EDAT,
	XCALL OUTPT (9,20,2,'ENTER ENDING ACTIVITY DATE',V)
	XCALL INPUT (9,52,6,0,'D ',ENTRY,INXCTL,V)
	GO TO (SDAT,SDAT), INXCTL
	HLDATE = ENTRY (1,6)
	IF (HLDATE.EQ.0) HLDATE = STDATE
	ADATE = HLDATE,'XX/XX/XX'
	XCALL OUTPT(9,52,0,ADATE,V)
	EDATE(1,2) = HLDATE(5,6)
	EDATE(3,6) = HLDATE(1,4)
	IF (HLDATE.EQ.0) CALL ALLDAT
	GOTO ITEM
ALLDAT,
	ALL = 'ALL DATES'
	SDATE = 0
	EDATE = 999999
	XCALL OUTPT(9,52,0,ALL,V)
	RETURN 
ITEM,
	STXCTL = 3
	XCALL STENO(STRTNO,ENDNO,'ITEM #',15,STXCTL,2)
	GO TO (END), STXCTL

	LPSW = 1
	XCALL LPON (LPSW,SPLFIL)
	IF (LPSW.NE.0) GO TO BEGIN2
	CALL CLOSE3
	GO TO EXIT
BEGIN2,
	WTARG = 2
	IF (LPSW.EQ.2) WTARG = 4
	XCALL WAIT(WTARG,V)
	XCALL IO (2,ITMIDX,1,READ,LOKCTL)
	GOTO HFORWD
NXTITM,
	LOKCTL = 1
	XCALL IOS (2,ITMIDX,READ,LOKCTL)
	IF (LOKCTL.EQ.2) GO TO LSTREC
	IF (IRC041.EQ.0) GOTO NXTITM
	IF (ITMIDX.EQ.']]]]]]') GOTO LSTREC
	IF (IITMNO.LT.STRTNO) GOTO NXTITM
	IF (IITMNO.GT.ENDNO) GO TO LSTREC
	LOKCTL = 1
	XCALL IO (1,ITMMAS,IRC041,READ,LOKCTL)
GETHST,
	UITMNO =
	FSTFLG =
	UDATE =
HFORWD,
	LOKCTL = 1
	XCALL IOS (8,INVHST,READ,LOKCTL)
	IF (UITMNO.EQ.']]]]]]') GOTO LSTREC
	IF (LOKCTL.EQ.2) GOTO LSTREC
;;	IF (UITMNO.NE.IITMNO) GOTO DASHES
;;	IF (UDATE.LT.SDATE .OR. UDATE.GT.EDATE) GOTO DASHES

	FSTFLG = 1
	PLINE(1,15) = UITMNO
	PLINE(19,26) = UDATE,DTMASK
	PLINE(30,37) = UQTY,'ZZZ,ZZX'
	PLINE(41,55) = UNUITM
	PLINE(59,61) = UTYPE
	CALL PRINT
	GOTO HFORWD
DASHES,
	PLINE(1,40) = DASHES
	PLINE(41,61) = DASHES
	CALL PRINT
	GOTO NXTITM
PRINT,
	IF (LINCNT.GE.57) LINCNT = 61
	XCALL LPOUT(LINCNT,PGCNT,PLINE,TITLE,HDR1,'NO HDR','NO HDR',
&			'NO LEGEND',' ',' ',0,132,PRTCTL,1,LPSW,RPTNUM,PRTTYP)
	RETURN
LSTREC,
	SAVLPS = LPSW
	XCALL LPOFF (LPSW,SPLFIL,PGCNT)
	IF (SAVLPS.EQ.2) GO TO END
	IF (SAVLPS.EQ.-4) PGCNT =
	GO TO BEGIN
END,
	CALL CLOSE3
EXIT,
	XCALL PGCHN('PO:POMENU',1)
CLOSE3,
	XCALL WAIT(3,V)
	XCALL FILES(1,'I',41,4)
	XCALL FILES(8,'SI',26,4)
CLOSE1,
	XCALL FILES(2,'I',42,4)
	RETURN
INUSE1,
	CALL CLOSE1
	GOTO EXIT

END
