;  POENMN / POR - D11
;
;	9-19-88: ADD OPTION TO MANUALLY MARK PO'S COMPLETE.
;
;
;
;
;
;
;
;		PURCHASE ORDER ENTRY MENU
;
;

RECORD
	ENTRY	,A3
	FAIL	,D1
	INXCTL	,D1
	LOKCTL	,D1
	MSGCTL	,D1,	5
	N	,D1
	NXTPGM	,A9
	PGM	,D2
	PROGNM	,9A9,	'PO:POADDH','PO:POBRLS','PO:POCNGH','PO:POADDL',
&			'PO:POCNGL','PO:POLDEL','PO:POHMRK','PO:POHDEL',
&			'PO:POEDLS'
	READ	,D1,	0
	RESTRT	,D1
	SWITCH	,D1
	TITLE	,2A29,	'DELETE CLOSED PURCHASE ORDERS',
&			'PURCHASE ORDER EDIT LIST     '
	V	,D1
PROC
	XCALL TERID (V)
	V = 1
BEGIN,
	FAIL =
	XCALL OUTPT (1,1,2,'PURCHASE ORDER ENTRY',1)
	XCALL OUTPT (6,20,0,'PLEASE SELECT APPLICATION',V)
	XCALL OUTPT (8,25,0,'1. ADD PURCHASE ORDER',V)
	XCALL OUTPT (09,25,0,'2. ADD RELEASE OF BLANKET P/O',V)
	XCALL OUTPT (10,25,0,'3. CHANGE/INQUIRE P/O HEADER',V)
	XCALL OUTPT (11,25,0,'4. ADD P/O LINE',V)
	XCALL OUTPT (12,25,0,'5. CHANGE/INQUIRE P/O LINE',V)
	XCALL OUTPT (13,25,0,'6. DELETE P/O LINE',V)
	XCALL OUTPT (14,25,0,'7. MANUALLY MARKED POS COMPLETE',V)
	XCALL OUTPT (15,25,0,'8. DELETE CLOSED PURCHASE ORDERS',V)
	XCALL OUTPT (16,25,0,'9. PURCHASE ORDER EDIT LIST',V)

INPUT,
	XCALL INPUT (6,47,1,0,'#E',ENTRY,INXCTL,V)
	GO TO (INPUT,CHECK), INXCTL
	PGM = ENTRY (1,2)
	IF (PGM.LT.1.OR.PGM.GT.9) GO TO INPUT
	RESTRT = 1
	IF (PGM.LT.8) XCALL PGCHN (PROGNM(PGM),RESTRT)
	NXTPGM = PROGNM(PGM)
CHECK,
	IF (INXCTL.EQ.2) NXTPGM = 'PO:POMENU'

	XCALL WATE (1,V)

	N = PGM - 7
	IF (INXCTL.NE.2) XCALL OUTPT (2,1,1,TITLE(N),V)

	SWITCH = 1
	XCALL FILES (1,'SI',151,SWITCH)		; OPEN FOR INPUT
	IF (SWITCH.EQ.9)
	  BEGIN
	    CALL INUSE1
	    GO TO BEGIN
	  END

	SWITCH = 1
	XCALL FILES (2,'SI',152,SWITCH) 	; OPEN FOR INPUT
	IF (SWITCH.EQ.9)
	  BEGIN
	    CALL INUSE2
	    GO TO BEGIN
	  END

	XCALL FILES (1,'SI',151,4)
	XCALL FILES (2,'SI',152,4)

	IF (INXCTL.EQ.2) XCALL PGCHN ('PO:POMENU',1)
	IF (PGM.EQ.7) CALL PROTCT
	IF (FAIL) GO TO BEGIN
	XCALL PGCHN (NXTPGM,1)

PROTCT,
	SWITCH = 3
	IF (INXCTL.EQ.2) SWITCH = 2
	XCALL FILES (1,'SU',151,SWITCH)	; PROTECT PORHDR
	IF (SWITCH.EQ.9) GO TO INUSE1

	SWITCH = 3
	IF (INXCTL.EQ.2) SWITCH = 2
	XCALL FILES (2,'SU',152,SWITCH)	; PROTECT PORLIN
	IF (SWITCH.EQ.9) GO TO INUSE2
	IF (INXCTL.NE.2) RETURN
	CLOSE 1
	CLOSE 2
	RETURN
;**********************************************************************

EXIT,
	XCALL FILES (2,'SU',152,4)
INUSE2,
	XCALL FILES (1,'SU',151,4)
INUSE1,
	RESTRT = 1
	IF (INXCTL.EQ.2) XCALL PGCHN ('PO:POMENU',RESTRT)
	FAIL = 1
	RETURN

;**********************************************************************

END

