;POPPOR.POR
;
;		POPULATE PURCHASE ORDER LINE FILE (PORNXF)
;
RECORD	FFILE
	FILNUM	,D3
	CLCTL	,D1
	REDFIL	,A14

RECORD	PORNXF
	.INCLUDE 'DEF:RD192A.DEF'

RECORD	PORLIN
	.INCLUDE 'DEF:RD152A.DEF'

RECORD	DIS
	I	,D5

RECORD	VARS
	V	,D1
	READ	,D1,0
	WRITE	,D1,1
	STORE	,D1,2
	LOKCTL	,D1



PROC
	XCALL TERID (V)
	DISPLAY (15,'REBUILD P.O. LINE ITEM CROSS REFERENCE FILE')

	FILNUM = 192
	XCALL FFILE (FILNUM,REDFIL,CLCTL)
	REDFIL(13,14) = 'SM'
	XCALL ISCLR (1,REDFIL,CLCTL)
	IF (CLCTL .NE. 0)
		BEGIN
		DISPLAY (15,FFILE)
		STOP
		END

	XCALL FILES (1,'SU',192,2)
	XCALL FILES (2,'SI',152,1)
	
	I = 1
LOOP,
	INCR I
;;	IF (I/25*25 .EQ. I) XCALL OUTPT (1,60,1,DIS,1)

	LOKCTL = 1
	XCALL IOS (2,PORLIN,READ,LOKCTL)
	IF (LOKCTL.NE.0) GOTO EOF

	PORPN = LJOBNO
	PORPO = LPONUM
	PORREL = LRLNUM
	PORLNO = LLINNO
	POPART = LITMNO
	XCALL ISIO (1,PORNXF,PNXKEY,STORE,LOKCTL)
	GOTO LOOP
EOF,
	XCALL FILES (2,'SI',152,4)
	XCALL FILES (1,'SU',192,4)
	STOP


END
