;  RSTQOO / POR - D11
;
;		THIS PROGRAM WILL ZERO ALL QUANTITY ON ORDER FIELDS IN THE
;		ITEM MASTER FILE, THEN SEQUENTIALLY READ THE PURCHASE ORDER
;		LINE ITEM FILE AND ACCUMULATE NEW QUANTITY ON ORDER AMOUNTS
;		FOR THE ITEM MASTER FILE.
;
;		THIS PROGRAM MAY BE RUN FROM THE POR "POSFMN" MENU 
;

RECORD INVTRX	
	.INCLUDE 'DEF:RD043A.DEF'

RECORD DUMTRX	
	.INCLUDE 'DEF:RD043B.DEF'

RECORD PORLIN  	
	.INCLUDE 'DEF:RD152A.DEF'

RECORD ITMMAS	
	.INCLUDE 'DEF:RD041A.DEF'

RECORD DUMINV	
	.INCLUDE 'DEF:RD041B.DEF'

RECORD ITMIDX	
	.INCLUDE 'DEF:RD042A.DEF'

RECORD PRDSTR	
	.INCLUDE 'DEF:RD091A.DEF'

RECORD
	PRGNAM	,A9
	SPLFIL	,A14
	V	,D1
	ENTRY	,A15
	SWITCH	,D1
	INXCTL	,D1
	CTR	,D5
	BSEND	,D5
	BSMID	,D5
	KEY	,A15
	SRCCTL	,D1
	MSGCTL	,D1
	MSG	,A54,	'BAD BILL - ITEM                 ; NO COMPONENT POSTING'
	BADBIL	,D1
	RECNO	,D5
	LOCTNS	,D2
	ORDNOA	,A6
	READ	,D1	,0
	WRITE	,D1	,1
	LOKCTL	,D1
	LPSW	,D2
	RPTNUM	,D3
	PRTTYP	,A1
	PGCNT	,D3
	LLOC	,A2
	LINCNT	,D2,	60


PROC
;>(01)
	XCALL TERID (V)
;;	XCALL OUTPT (1,1,2,'RESET QUANTITY ON ORDER FIELDS IN ITEM MASTER FILE',V)
;;	XCALL OUTPT (5,9,0,
;;&	'This program will Zero all QTYONO fields in the ITMMAS file and ',V)
;;	XCALL OUTPT (6,9,0,
;;&	'reset those fields per Quantities from orders in the PORLIN file',V)
;;	XCALL OUTPT (7,17,0,'ARE YOU SURE YOU WANT TO RESET THIS FIELDS ?',V)
;	XCALL INPUT (7,64,1,1,'YE',ENTRY,INXCTL,V)
;	IF (INXCTL.NE.1) XCALL PGCHN('PO:POSFMN',1)
;	LPSW = 3	; NOT DISPLAYABLE
;	XCALL LPON (LPSW,SPLFIL)
;	IF (LPSW.EQ.0) XCALL PGCHN ('PO:POSFMN',1)
;;	XCALL WAIT (4,V)		;PROCESSING MESSAGE
;<(01)
	DISPLAY (15,'RESET QUANTITY ON ORDER FIELDS IN ITEM MASTER FILE',V)

	SWITCH = 5
	XCALL FILES (2,'I',42,SWITCH)			;FILE #42 -- ITMIDX
	IF (SWITCH.EQ.9) GO TO END1
	SWITCH = 5
	XCALL FILES (1,'U',41,SWITCH)			;FILE #41 -- ITMMAS
	IF (SWITCH.EQ.9) GO TO END2
	SWITCH = 5
	XCALL FILES (5,'SI',152,SWITCH)			;FILE #152 -- PORLIN
	IF (SWITCH.EQ.9) GO TO END3
	SWITCH = 5
	XCALL FILES (13,'I',43,SWITCH)			;FILE #43 -- INVTRX
	IF (SWITCH.EQ.9) GO TO END4

;;	SWITCH = 5
;;	XCALL FILES (2,'I',42,SWITCH)
;;	SWITCH = 5
;;	XCALL FILES (1,'U',41,SWITCH)
;;	SWITCH = 5

	LOKCTL = 1
	XCALL IO (1,DUMINV,1,READ,LOKCTL)
	IF (TYPSYS.LE.2) GO TO NOBMP

	SWITCH = 1
	XCALL FILES (12,'SI',91,SWITCH)			;FILE #91 -- PRDSTR
	IF (SWITCH.EQ.9) GO TO END5

	SWITCH = 5
	XCALL FILES (6,'SI',91,SWITCH)

NOBMP,
	LOCTNS = NUMLOC
	LLOC = 'SR'
;(01)	XCALL OUTPT (10,1,0,'PASS 1 - CLEAR OLD ON ORDER -  ITEM:',V)
;;;	DISPLAY (15,'PASS 1 - CLEAR OLD ON ORDER -  ITEM:',V)
	IRC041 = 1
PASS1,
	INCR IRC041
	LOKCTL = 1
	XCALL IO (1,ITMMAS,IRC041,READ,LOKCTL)
	IF (DESCR.EQ.']]]DEL') GO TO PASS1	;DELETED RECORD
	IF (DESCR.EQ.']]]]]]'.OR.IRC041.GT.REC041) GO TO EOPAS1
;;;	XCALL OUTPT (10,38,0,ITEMNO,V)
	CTR =
CLR,
	INCR CTR
	IF (CTR.GT.5) GO TO ENDCLR
	QTYONO (CTR) =
	GO TO CLR
ENDCLR,
	LOKCTL = 1
	XCALL IO (1,ITMMAS,IRC041,WRITE,LOKCTL)
	GO TO PASS1
EOPAS1,
	CALL COPPAS
	GOTO EOPAS3
COPPAS,
;(01)	XCALL OUTPT (10,1,1,'PASS 2   PURCHASE ORDER #:',V)
PASS2,
	LOKCTL = 1
	XCALL IOS (5,PORLIN,READ,LOKCTL)
	IF (LOKCTL.EQ.2) GO TO EOF
	IF (LQTYOR.EQ.0) GO TO PASS2
	KEY = LITMNO
	BSEND = ORG041
	XCALL SERCH (2,ITMIDX,KEY,1,15,BSEND,BSMID,SRCCTL,4,16,20,0,0,0,0)
	IF (SRCCTL.OR.IRC041.EQ.0) GO TO PASS2
	LOKCTL = 1
	XCALL IO (1,ITMMAS,IRC041,READ,LOKCTL)
;;	ORDNOA = LPONUM, 'ZZZZZX'
;;	XCALL OUTPT (10,28,0,ORDNOA,V)
;;	XCALL OUTPT (0,0,0,'   ITEM: ',V)
;;	XCALL OUTPT (0,0,0,ITEMNO,V)
	IF (STOKED.NE.'S'.AND.TYPSYS.GE.3) GO TO NONSTK
	IF (CNTRLD.NE.'C') GO TO PASS2
	CTR =
FNDLC1,
	INCR CTR
	IF (CTR.GT.LOCTNS.OR.LOC(CTR).EQ.'  ') GO TO PASS2
	IF (LOC(CTR).NE.LLOC) GO TO FNDLC1
	QTYONO (CTR) = QTYONO (CTR) + (LQTYOR-LQTYRC)
	IF (QTYONO(CTR).LT.0) QTYONO(CTR) = 
	LOKCTL = 1
	XCALL IO (1,ITMMAS,IRC041,WRITE,LOKCTL)
	IF (STOKED.EQ.'S'.OR.TYPSYS.LE.2) GO TO PASS2
NONSTK,
	KEY = ITEMNO
	LOKCTL = 1
	XCALL ISIO (12,PRDSTR,KEY,READ,LOKCTL)
	IF (LOKCTL.NE.0) GO TO PASS2
	IF (PITMNO.NE.ITEMNO) GO TO PASS2
	XCALL QOOSB (LITMNO,LQTYOR,LOCTNS,BADBIL,LINCNT,PGCNT,
&	LPSW,RPTNUM,PRTTYP)
	IF (BADBIL.EQ.1) GO TO BILERR
	GO TO PASS2
EOF,
	RETURN
NORST,
;;	XCALL MESAG('MUST POST INVENTORY TRX BEFORE RESETTING',1)
	GOTO END5
;*******************************************************
EOPAS3,
;>(01)
;;	XCALL WAIT(3,V)
;	XCALL LPOFF (LPSW,SPLFIL,PGCNT)
;;	IF (TYPSYS.GE.3) XCALL FILES (12,'I',91,4)
	IF (TYPSYS.GE.3) CLOSE 12
	IF (TYPSYS.GE.3) CLOSE 6
	XCALL FILES (13,'I',43,4)
	XCALL FILES (1,'U',41,4)
	XCALL FILES (2,'I',42,4)
	XCALL FILES (5,'SI',152,4)
	STOP
;;	XCALL PGCHN ('PO:POSFMN',1)
END5,
	XCALL FILES (13,'I',43,4)
END4,
	XCALL FILES (5,'SI',152,4)
END3,
	XCALL FILES(1,'U',41,4)
END2,
	XCALL FILES(2,'I',42,4)
END1,
;	XCALL LPOFF (LPSW,SPLFIL,PGCNT)
;;	XCALL WAIT (3,V)
	STOP
;;	XCALL PGCHN ('PO:POSFMN',1)
BILERR,
;;	MSG (17,31) = ITEMNO
;	XCALL LPOUT (LINCNT,PGCNT,MSG,'NO TITLE','NO HDR',' ',' ',
;&	'NO LEGEND',' ',' ',0,132,0,0,LPSW,RPTNUM,PRTTYP)
	GO TO PASS2
END
