;VIMENU.POR
;
;
;
;
;
;
;		INVENTORY/VENDOR PART # XREF MENU
RECORD
	ENTRY	,A3
	INXCTL	,D1
	PGM	,D2
	PROGNM	,5A9,	'PO:PARTN1','PO:PARTV1','PO:VCRRPT','PO:NUVRPT','PO:NUVRP2'
	RESTRT	,D1
	V	,D1
	NXTPGM	,A9
	SWITCH	,D1
	LOKCTL	,D1
	READ	,D1,	0
PROC
	XCALL TERID (V)
BEGIN,
	XCALL OUTPT (1,1,2,'INVENTORY/VENDOR PART CROSS REFERENCE',1)
	XCALL OUTPT (5,20,0,'PLEASE SELECT FUNCTION',V)
	XCALL OUTPT (6,25,0,'1. VENDOR/INVENTORY X-REF',V)
	XCALL OUTPT (7,25,0,'2. VENDOR PART # MAINTENANCE',V)
	XCALL OUTPT (8,25,0,'3. VENDOR/INVENTORY REPORT BY VENDOR #',V)
	XCALL OUTPT (9,25,0,'4. VENDOR/INVENTORY REPORT BY NU-AIRE #',V)
	XCALL OUTPT(10,25,0,'5. VENDOR/INVENTORY REPORT BY COMM CODE',V)
INPUT,
	XCALL INPUT (5,44,1,0,'#E',ENTRY,INXCTL,V)
	GO TO (INPUT,EXIT), INXCTL
	PGM = ENTRY (1,1)
	IF (PGM.LT.1.OR.PGM.GT.5) GO TO INPUT
	RESTRT = 1
	XCALL PGCHN (PROGNM(PGM),RESTRT)
;**********************************************************************
EXIT,
	RESTRT = 1
	XCALL PGCHN ('PO:POMENU',RESTRT)
;**********************************************************************

END

