;  OEMNU / COP 
;
;		PROGRAM TO DISPLAY OE MENU AND CHAIN TO APPROPRIATE PROGRAM
;
;
	.INCLUDE 'WND:TOOLS.DEF'

RECORD	VARS
	DCHAR	,D3
	ALPHA	,A3
	DEC	,D2
	DEC3	,D3
	TTWAIT	,D1
	CHAR_ON	,D1
	ENTRY	,A30
	INXCTL	,D1
	MODE	,10A11,'ENTER     ','INQUIRE   ','MWRORD    ','CANCEL     ',
&		      'PRINT OUT ','COPY ORD  ','COPY ROC  ','RE-COPY ROC',
&		      'REVERSE   ','COMMENTS  '
	OPTION	,D2
	V	,D1
PROC
	XCALL TERID (V)
BEGIN,
	CLEAR CHAR_ON
	XCALL OUTPT (1,1,2,'ORDER ENTRY & EDITING',V)
	XCALL OUTPT (2,20,0,'PLEASE SELECT APPLICATION',V)
	XCALL OUTPT (3,25,0,'1. MAINTAIN ORDERS',V)
	XCALL OUTPT (4,25,0,'2. INQUIRE ORDERS',V)
	XCALL OUTPT (5,25,0,'3. NEW INQUIRE',V)
	XCALL OUTPT (6,25,0,'4. CANCEL ORDERS',V)
	XCALL OUTPT (7,25,0,'5. PRINT OUT ORDERS',V)
	XCALL OUTPT (8,25,0,'6. COPY OLD ORDER',V)
	XCALL OUTPT (9,25,0,'7. COPY ROC ORDER',V)
	XCALL OUTPT (10,25,0,'8. RE-COPY ROC ORDER',V)
	XCALL OUTPT (11,25,0,'9. REVERSE INQUIRY',V)
	XCALL OUTPT (12,24,0,'10. OPEN ORDER COMMENTS',V)

	XCALL OUTPT (2,47,0,'\',V)
INPUT,
	XCALL INPUT(2,47,2,1,'#E',ENTRY,INXCTL,V)
	GOTO (BEGIN, END),INXCTL

	OPTION = ENTRY(1,2)
	IF (OPTION.LT.1.OR.OPTION.GT.10) GO TO BEGIN
	IF (OPTION .EQ. 4) GOTO BEGIN
	XCALL OUTPT (2,1,0,MODE(OPTION),1)
	GO TO (ADD,INQUIR,NQUIRE,BEGIN,EDIT,FLAG,ROC,RE_ROC,REVRS), OPTION
	GOTO (COMMENT),OPTION-9
ADD,
	XCALL PGCHN ('CP:ORDMNT',1)
INQUIR,
	XCALL PGCHN ('CP:INQUIR',1)
NQUIRE,
	XCALL PGCHN ('CP:NQUIRE',1)
CHANGE,
	XCALL PGCHN ('CP:CHANGE',1)
CANCEL,
	XCALL PGCHN ('CP:CANCEL',1)
EDIT,
	XCALL PGCHN ('CP:ORDEDT',1)
FLAG,
	XCALL PGCHN ('CP:CPYORD',1)
;;;	XCALL PGCHN ('CP:OSTATS',1)
ROC,
	XCALL PGCHN ('CP:CPYROC',1)
RE_ROC,
	XCALL PGCHN ('CP:REROCK',1)

REVRS,
	XCALL PGCHN ('CP:RQUIRE',1)
COMMENT,
	XCALL PGCHN ('CP:OOCMNT',1)
END,
	XCALL OUTPT (2,47,1,'END',V)
	XCALL PGCHN ('CP:CPMENU',1)
END
