; TERMSD / COP 
;
;
; 6-04-18 ssq: make cusmas isam
;

RECORD CUSMAS		
		.INCLUDE 'DEF:RD001A.DEF'
RECORD,X
		.INCLUDE 'DEF:RD001B.DEF'

RECORD
	V	,D1
	SWITCH	,D1
	ARRSIZ	,D2	,30	;VALUE IS ARRAY SIZE USUALLY 30
	ARPNTR	,D2
	CTR	,D2
	WROW	,D2
	WCOL	,D3
	HDCNTA	,A3
	HDCNTR	,D2
	ENTRY	,A6
	INXCTL	,D1
	WCUSNO	,D6
	CNGCTL	,D1
	WHATNO	,D2
	TCHAR	,D3
	SELECT	,D1
	DISCA	,A4
	ARRCNT	,D2
	COL2	,D2
	ROW2	,D2
	READ	,D1	,0
	WRITE	,D1	,1
	LOKCTL	,D1
PROC
	XCALL TERID(V)
	SWITCH = 1
	XCALL FILES(1,'SU',01,SWITCH)		;FILE#01 -- CUSMAS FILE
	IF (SWITCH.EQ.9) GO TO END
	LOKCTL = 1

	CUSNO = 0
	XCALL ISIO (1,CUSMAS,CUSNO,READ,LOKCTL)
	CNGCTL =
	IF (TPRDCD(1).NE.'  ') CNGCTL = 1
DISPLA,
	XCALL OUTPT (1,1,2,'TERMS DISCOUNT MAINTENANCE',V)
	XCALL OUTPT (2,4,0,'PROD   DISC',V)
	XCALL OUTPT (2,21,0,'PROD   DISC',V)
	XCALL OUTPT (2,38,0,'PROD   DISC',V)
	XCALL OUTPT (2,55,0,'PROD   DISC',V)
	HDCNTR =
LOOP01,
	INCR HDCNTR
	IF (HDCNTR.GE.(ARRSIZ+1)) GO TO MODE
	IF (HDCNTR.GT.27) GOTO COLFOR
	IF (HDCNTR.GT.18) GOTO COLTRE
	IF (HDCNTR.GT.9) GOTO COLTWO
COLONE,
	WCOL = 32
	WROW = HDCNTR + 2
	GOTO DSPHDR
COLTWO,
	WCOL = 48
	WROW = HDCNTR - 7
	GOTO DSPHDR
COLTRE,
	WCOL = 65
	WROW = HDCNTR - 16
	GOTO DSPHDR
COLFOR,
	WCOL = 82
	WROW = HDCNTR - 25
	GOTO DSPHDR
DSPHDR,
	HDCNTA = HDCNTR,'ZX.'
	COL2 = WCOL-31
	XCALL OUTPT (WROW,COL2,0,HDCNTA,V)
	GOTO LOOP01
MODE,
	IF (CNGCTL.NE.0) GO TO CHANGE
	ARPNTR =
NEW1,
	INCR ARPNTR
	IF (ARPNTR.GT.30) GO TO ANYCNG
	HDCNTR = ARPNTR
ADDENT,
	IF (HDCNTR.GT.27) GOTO COLMFR
	IF (HDCNTR.GT.18) GOTO COLMTH
	IF (HDCNTR.GT.9) GOTO COLMTW
COLMON,
	WCOL = 5
	WROW = HDCNTR + 2
	GOTO ENTER
COLMTW,
	WCOL = 22
	WROW = HDCNTR - 7
	GOTO ENTER
COLMTH,
	WCOL = 39
	WROW = HDCNTR - 16
	GOTO ENTER
COLMFR,
	WCOL = 56
	WROW = HDCNTR - 25
	GOTO ENTER
ENTER,
	XCALL INPUT (WROW,WCOL,02,00,'A ',ENTRY,INXCTL,V)
	GOTO (DISPLA), INXCTL
	IF (ENTRY(1,2).EQ.'  '.AND.CNGCTL.EQ.0) GO TO CHANGE
	TPRDCD(ARPNTR) = ENTRY(1,2)
	IF (ENTRY(1,2).EQ.'  ') GOTO DELETE
NODUPS,
	CTR =
NODUP1,
	INCR CTR
	IF (CTR.GE.ARPNTR) GOTO ITISOK
	IF (TPRDCD(ARPNTR).EQ.TPRDCD(CTR)) GOTO BAD1
	GOTO NODUP1
BAD1,
	XCALL MESAG('DUPLICATE CODES NOT ALLOWED',1)
	GOTO ENTER
ITISOK,
	XCALL OUTPT (WROW,WCOL,0,TPRDCD(ARPNTR),V)
ENTER1,
	WCOL = WCOL + 6
	XCALL INPUT (WROW,WCOL,02,00,'# ',ENTRY,INXCTL,V)
	GOTO (ENTER), INXCTL
	TDISC(ARPNTR) = ENTRY(1,2)
	DISCA = TDISC(ARPNTR),'X.X%'
	XCALL OUTPT (WROW,WCOL,0,DISCA,V)
	IF (CNGCTL.EQ.0) INCR ARRCNT
	GO TO (NEW1,ANYCNG), CNGCTL + 1
CHANGE,
	CALL DSPARR
ANYCNG,
	XCALL ANYCN(CNGCTL,WHATNO)
	GO TO (PROCES,CNGBR), CNGCTL + 1
CNGBR,
	IF (WHATNO.LT.1.OR.WHATNO.GE.(ARRSIZ+1)) GOTO ANYCNG
	IF (WHATNO.EQ.(ARRCNT+1)) INCR ARRCNT
	IF (WHATNO.GT.(ARRCNT+1)) CALL FIX
	HDCNTR = WHATNO
	ARPNTR = WHATNO
	GO TO ADDENT
DSPARR,
	HDCNTR =
	ARRCNT =
LOOP02,
	INCR HDCNTR
	IF (HDCNTR.GT.ARRSIZ) RETURN
	IF (TPRDCD(HDCNTR).NE.'  ') INCR ARRCNT
	IF (HDCNTR.GT.27) GOTO COLIV
	IF (HDCNTR.GT.18) GOTO COLIII
	IF (HDCNTR.GT.9) GOTO COLII
COLI,
	WCOL = 36
	WROW = HDCNTR + 2
	GOTO DSPDIS
COLII,
	WCOL = 53
	WROW = HDCNTR - 7
	GOTO DSPDIS
COLIII,
	WCOL = 70
	WROW = HDCNTR - 16
	GOTO DSPDIS
COLIV,
	WCOL = 87
	WROW = HDCNTR - 25
	GOTO DSPDIS
DSPDIS,
	DISCA = TDISC(HDCNTR),'X.X%'
	IF (TPRDCD(HDCNTR).EQ.'  ') DISCA = TDISC(HDCNTR),'ZZ'
	COL2 = WCOL-31
	XCALL OUTPT (WROW,COL2,0,TPRDCD(HDCNTR),V)
	COL2 = WCOL+2-31
	XCALL OUTPT (WROW,COL2,0,'    ',V)
	COL2 = WCOL+6-31
	XCALL OUTPT (WROW,COL2,0,DISCA,V)
	GOTO LOOP02
DELETE,
	IF (TPRDCD(ARPNTR+1).EQ.'  '.OR.(ARPNTR+1).GT.ARRSIZ) GOTO CLRSPT
	TPRDCD(ARPNTR) = TPRDCD(ARPNTR+1)
	TDISC(ARPNTR) = TDISC(ARPNTR+1)
	INCR ARPNTR
	GOTO DELETE
CLRSPT,
	TPRDCD(ARPNTR) =
	TDISC(ARPNTR) =
	CALL DSPARR
	GOTO ANYCNG
FIX,
	INCR ARRCNT
	WHATNO = ARRCNT
	RETURN
PROCES,
	XCALL WATE(3,V)
	LOKCTL = 1
	XCALL ISIO (1,CUSMAS,CUSNO,WRITE,LOKCTL)
	CLOSE 1
END1,
	XCALL FILES (1,'SI',01,4)
END,
	XCALL PGCHN ('CP:SPCFUN',1)
	END
