; UNPRSA / COP - D11
;
;
;		ROUTINE TO TURN OFF FILE PROTECTION IF USER
;		DOESN'T WANT TO WAIT FOR PRINTER WHILE IN
;		OE SALES ANALYSIS JOB STREAM
;
RECORD
	V	,D1
PROC
	XCALL TERID (V)
	XCALL FILES(9,'I',49,4)			;FILE # 49 -- SAPIDX FILE
	XCALL FILES(2,'I',42,4)			;FILE # 42 -- INVIDX FILE
	XCALL PGCHN ('CP:CPMENU',1)
	END
